# Iosevka Matsuri
[buildPlans.IosevkaMatsuri]
family = "Iosevka Matsuri"
spacing = "normal"
serifs = "sans"
exportGlyphNames = true

[buildPlans.IosevkaMatsuri.variants]
inherits = "ss14"

[buildPlans.IosevkaMatsuri.variants.design]
capital-a = "straight-serifless"
capital-b = "standard-serifless"
capital-c = "serifless"
capital-d = "more-rounded-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-h = "serifless"
capital-i = "serifed"
capital-j = "serifed"
capital-k = "symmetric-touching-serifless"
capital-l = "serifless"
capital-m = "slanted-sides-hanging-serifless"
capital-n = "standard-serifless"
capital-p = "closed-serifless"
capital-q = "crossing"
capital-r = "standing-serifless"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-rounded-serifless"
capital-v = "straight-serifless"
capital-w = "straight-serifless"
capital-x = "straight-serifless"
capital-y = "straight-serifless"
capital-z = "straight-serifless"
a = "single-storey-earless-rounded-serifless"
b = "toothless-rounded-serifless"
c = "serifless"
d = "toothless-rounded-serifless"
e = "flat-crossbar"
f = "serifless"
g = "single-storey-earless-rounded"
h = "straight-serifless"
i = "serifed-flat-tailed"
j = "flat-hook-serifed"
k = "symmetric-touching-serifless"
l = "serifed-flat-tailed"
m = "earless-rounded-double-arch-short-leg-serifless"
n = "earless-rounded-straight-serifless"
p = "earless-rounded-serifless"
q = "earless-rounded-straight-serifless"
r = "earless-rounded-serifless"
s = "serifless"
t = "flat-hook"
u = "toothless-rounded-serifless"
v = "straight-serifless"
w = "straight-serifless"
x = "straight-serifless"
y = "straight-serifless"
z = "straight-serifless"
zero = "slashed"
one = "no-base"
two = "straight-neck"
three = "flat-top"
four = "closed-non-crossing"
five = "upright-flat"
six = "straight-bar"
seven = "bend-serifless"
eight = "two-circles"
nine = "straight-bar"
punctuation-dot = "round"
tilde = "low"
asterisk = "penta-low"
underscore = "low"
caret = "low"
paren = "large-contour"
brace = "curly"
number-sign = "slanted"
ampersand = "upper-open"
at = "compact"
dollar = "interrupted"
cent = "bar-interrupted"
percent = "dots"
question = "smooth"

[buildPlans.IosevkaMatsuri.variants.italic]
capital-a = "curly-serifless"
capital-b = "standard-serifless"
capital-c = "serifless"
capital-d = "more-rounded-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-h = "serifless"
capital-i = "serifed"
capital-j = "serifed"
capital-k = "symmetric-touching-serifless"
capital-l = "serifless"
capital-m = "slanted-sides-hanging-serifless"
capital-n = "standard-serifless"
capital-p = "closed-serifless"
capital-q = "crossing"
capital-r = "standing-serifless"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-rounded-serifless"
capital-v = "curly-serifless"
capital-w = "curly-serifless"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "curly-serifless"
a = "single-storey-earless-rounded-serifless"
b = "toothless-rounded-serifless"
c = "serifless"
d = "toothless-rounded-serifless"
e = "rounded"
f = "tailed"
g = "single-storey-earless-rounded"
h = "straight-serifless"
i = "tailed-serifed"
j = "serifed"
k = "cursive-serifless"
l = "tailed-serifed"
m = "earless-rounded-double-arch-short-leg-serifless"
n = "earless-rounded-straight-serifless"
p = "earless-rounded-serifless"
q = "earless-rounded-straight-serifless"
r = "earless-rounded-serifless"
s = "serifless"
t = "bent-hook"
u = "toothless-rounded-serifless"
v = "cursive-serifless"
w = "cursive-serifless"
x = "curly-serifless"
y = "cursive-serifless"
z = "curly-serifless"
zero = "slashed"
one = "no-base"
two = "straight-neck"
three = "flat-top"
four = "closed-non-crossing"
five = "upright-flat"
six = "straight-bar"
seven = "bend-serifless"
eight = "two-circles"
nine = "straight-bar"
punctuation-dot = "round"
tilde = "low"
asterisk = "penta-low"
underscore = "low"
caret = "low"
paren = "large-contour"
brace = "curly"
number-sign = "slanted"
ampersand = "upper-open"
at = "compact"
dollar = "interrupted"
cent = "bar-interrupted"
percent = "dots"
question = "smooth"

[buildPlans.IosevkaMatsuri.ligations]
inherits = "dlig"

[buildPlans.IosevkaMatsuri.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.IosevkaMatsuri.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaMatsuri.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.IosevkaMatsuri.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.IosevkaMatsuri.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaMatsuri.weights.ExtraBold]
shape = 800
menu = 800
css = 800

[buildPlans.IosevkaMatsuri.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.IosevkaMatsuri.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaMatsuri.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

# Iosevka Matsuri Term
[buildPlans.IosevkaMatsuriTerm]
family = "Iosevka Matsuri Term"
spacing = "term"
serifs = "sans"
exportGlyphNames = true

[buildPlans.IosevkaMatsuriTerm.variants]
inherits = "ss14"

[buildPlans.IosevkaMatsuriTerm.variants.design]
capital-a = "straight-serifless"
capital-b = "standard-serifless"
capital-c = "serifless"
capital-d = "more-rounded-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-h = "serifless"
capital-i = "serifed"
capital-j = "serifed"
capital-k = "symmetric-touching-serifless"
capital-l = "serifless"
capital-m = "slanted-sides-hanging-serifless"
capital-n = "standard-serifless"
capital-p = "closed-serifless"
capital-q = "crossing"
capital-r = "standing-serifless"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-rounded-serifless"
capital-v = "straight-serifless"
capital-w = "straight-serifless"
capital-x = "straight-serifless"
capital-y = "straight-serifless"
capital-z = "straight-serifless"
a = "single-storey-earless-rounded-serifless"
b = "toothless-rounded-serifless"
c = "serifless"
d = "toothless-rounded-serifless"
e = "flat-crossbar"
f = "serifless"
g = "single-storey-earless-rounded"
h = "straight-serifless"
i = "serifed-flat-tailed"
j = "flat-hook-serifed"
k = "symmetric-touching-serifless"
l = "serifed-flat-tailed"
m = "earless-rounded-double-arch-short-leg-serifless"
n = "earless-rounded-straight-serifless"
p = "earless-rounded-serifless"
q = "earless-rounded-straight-serifless"
r = "earless-rounded-serifless"
s = "serifless"
t = "flat-hook"
u = "toothless-rounded-serifless"
v = "straight-serifless"
w = "straight-serifless"
x = "straight-serifless"
y = "straight-serifless"
z = "straight-serifless"
zero = "slashed"
one = "no-base"
two = "straight-neck"
three = "flat-top"
four = "closed-non-crossing"
five = "upright-flat"
six = "straight-bar"
seven = "bend-serifless"
eight = "two-circles"
nine = "straight-bar"
punctuation-dot = "round"
tilde = "low"
asterisk = "penta-low"
underscore = "low"
caret = "low"
paren = "large-contour"
brace = "curly"
number-sign = "slanted"
ampersand = "upper-open"
at = "compact"
dollar = "interrupted"
cent = "bar-interrupted"
percent = "dots"
question = "smooth"

[buildPlans.IosevkaMatsuriTerm.variants.italic]
capital-a = "curly-serifless"
capital-b = "standard-serifless"
capital-c = "serifless"
capital-d = "more-rounded-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-h = "serifless"
capital-i = "serifed"
capital-j = "serifed"
capital-k = "symmetric-touching-serifless"
capital-l = "serifless"
capital-m = "slanted-sides-hanging-serifless"
capital-n = "standard-serifless"
capital-p = "closed-serifless"
capital-q = "crossing"
capital-r = "standing-serifless"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-rounded-serifless"
capital-v = "curly-serifless"
capital-w = "curly-serifless"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "curly-serifless"
a = "single-storey-earless-rounded-serifless"
b = "toothless-rounded-serifless"
c = "serifless"
d = "toothless-rounded-serifless"
e = "rounded"
f = "tailed"
g = "single-storey-earless-rounded"
h = "straight-serifless"
i = "tailed-serifed"
j = "serifed"
k = "cursive-serifless"
l = "tailed-serifed"
m = "earless-rounded-double-arch-short-leg-serifless"
n = "earless-rounded-straight-serifless"
p = "earless-rounded-serifless"
q = "earless-rounded-straight-serifless"
r = "earless-rounded-serifless"
s = "serifless"
t = "bent-hook"
u = "toothless-rounded-serifless"
v = "cursive-serifless"
w = "cursive-serifless"
x = "curly-serifless"
y = "cursive-serifless"
z = "curly-serifless"
zero = "slashed"
one = "no-base"
two = "straight-neck"
three = "flat-top"
four = "closed-non-crossing"
five = "upright-flat"
six = "straight-bar"
seven = "bend-serifless"
eight = "two-circles"
nine = "straight-bar"
punctuation-dot = "round"
tilde = "low"
asterisk = "penta-low"
underscore = "low"
caret = "low"
paren = "large-contour"
brace = "curly"
number-sign = "slanted"
ampersand = "upper-open"
at = "compact"
dollar = "interrupted"
cent = "bar-interrupted"
percent = "dots"
question = "smooth"

[buildPlans.IosevkaMatsuriTerm.ligations]
inherits = "dlig"

[buildPlans.IosevkaMatsuriTerm.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.IosevkaMatsuriTerm.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaMatsuriTerm.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.IosevkaMatsuriTerm.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.IosevkaMatsuriTerm.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaMatsuriTerm.weights.ExtraBold]
shape = 800
menu = 800
css = 800

[buildPlans.IosevkaMatsuriTerm.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.IosevkaMatsuriTerm.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaMatsuriTerm.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
